# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Usuario\PycharmProjects\CrossEditorModel\UIS\BASE_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 712)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PrincipalGrid = QtWidgets.QWidget(MainWindow)
        self.PrincipalGrid.setObjectName("PrincipalGrid")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PrincipalGrid)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, 15, 20, 15)
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.PrincipalGrid)
        self.radioButton_4.setStyleSheet("font: 8pt \"Segoe MDL2 Assets\";")
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setAutoRepeat(False)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_3.addWidget(self.radioButton_4, 0, QtCore.Qt.AlignHCenter)
        self.radioButton_3 = QtWidgets.QRadioButton(self.PrincipalGrid)
        self.radioButton_3.setStyleSheet("font: 8pt \"Segoe MDL2 Assets\";")
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_3.addWidget(self.radioButton_3, 0, QtCore.Qt.AlignHCenter)
        self.radioButton_2 = QtWidgets.QRadioButton(self.PrincipalGrid)
        self.radioButton_2.setStyleSheet("font: 8pt \"Segoe MDL2 Assets\";")
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2, 0, QtCore.Qt.AlignHCenter)
        self.radioButton = QtWidgets.QRadioButton(self.PrincipalGrid)
        self.radioButton.setStyleSheet("font: 8pt \"Segoe MDL2 Assets\";")
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignBottom)
        self.pushButton_4 = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignBottom)
        self.pushButton_7 = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignBottom)
        self.pushButton_6 = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignBottom)
        self.pushButton_9 = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9, 0, QtCore.Qt.AlignBottom)
        self.pushButton_8 = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8, 0, QtCore.Qt.AlignBottom)
        self.widget = QtWidgets.QWidget(self.PrincipalGrid)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.SolarPanel = QtWidgets.QWidget(self.PrincipalGrid)
        self.SolarPanel.setMinimumSize(QtCore.QSize(1000, 540))
        self.SolarPanel.setBaseSize(QtCore.QSize(500, 400))
        self.SolarPanel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SolarPanel.setObjectName("SolarPanel")
        self.gridLayout_3.addWidget(self.SolarPanel, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.PrincipalGrid)
        self.label.setMinimumSize(QtCore.QSize(300, 75))
        self.label.setMaximumSize(QtCore.QSize(300, 75))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("CrossEditorProjectIcon.png"))
        self.label.setScaledContents(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 5)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButton_2.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";\n"
"selection-background-color: rgb(255, 255, 127);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.PrincipalGrid)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButton.setStyleSheet("font: 10pt \"Segoe MDL2 Assets\";")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.LeftMenu = QtWidgets.QToolBox(self.PrincipalGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftMenu.sizePolicy().hasHeightForWidth())
        self.LeftMenu.setSizePolicy(sizePolicy)
        self.LeftMenu.setMinimumSize(QtCore.QSize(300, 0))
        self.LeftMenu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LeftMenu.setAutoFillBackground(False)
        self.LeftMenu.setStyleSheet("font: 10pt \"Segoe MDL2 Assets\";\n"
"background-color: rgb(255, 255, 255);")
        self.LeftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenu.setLineWidth(5)
        self.LeftMenu.setObjectName("LeftMenu")
        self.P1 = QtWidgets.QWidget()
        self.P1.setGeometry(QtCore.QRect(0, 0, 300, 325))
        self.P1.setObjectName("P1")
        self.LeftMenu.addItem(self.P1, "")
        self.P2 = QtWidgets.QWidget()
        self.P2.setGeometry(QtCore.QRect(0, 0, 300, 325))
        self.P2.setObjectName("P2")
        self.LeftMenu.addItem(self.P2, "")
        self.P3 = QtWidgets.QWidget()
        self.P3.setGeometry(QtCore.QRect(0, 0, 300, 325))
        self.P3.setObjectName("P3")
        self.LeftMenu.addItem(self.P3, "")
        self.P4 = QtWidgets.QWidget()
        self.P4.setGeometry(QtCore.QRect(0, 0, 300, 325))
        self.P4.setObjectName("P4")
        self.LeftMenu.addItem(self.P4, "")
        self.P5 = QtWidgets.QWidget()
        self.P5.setGeometry(QtCore.QRect(0, 0, 300, 325))
        self.P5.setObjectName("P5")
        self.LeftMenu.addItem(self.P5, "")
        self.P6 = QtWidgets.QWidget()
        self.P6.setGeometry(QtCore.QRect(0, 0, 300, 325))
        self.P6.setObjectName("P6")
        self.LeftMenu.addItem(self.P6, "")
        self.P7 = QtWidgets.QWidget()
        self.P7.setGeometry(QtCore.QRect(0, 0, 300, 325))
        self.P7.setObjectName("P7")
        self.LeftMenu.addItem(self.P7, "")
        self.verticalLayout.addWidget(self.LeftMenu)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.PrincipalGrid)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1332, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHOLA = QtWidgets.QMenu(self.menuBar)
        self.menuHOLA.setObjectName("menuHOLA")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoad_Simple_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Simple_Image.setObjectName("actionLoad_Simple_Image")
        self.actionSet_of_Images = QtWidgets.QAction(MainWindow)
        self.actionSet_of_Images.setObjectName("actionSet_of_Images")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout_Interface = QtWidgets.QAction(MainWindow)
        self.actionAbout_Interface.setObjectName("actionAbout_Interface")
        self.actionAbout_Commands = QtWidgets.QAction(MainWindow)
        self.actionAbout_Commands.setObjectName("actionAbout_Commands")
        self.actionChange_settings = QtWidgets.QAction(MainWindow)
        self.actionChange_settings.setObjectName("actionChange_settings")
        self.menuHOLA.addSeparator()
        self.menuHOLA.addAction(self.actionLoad_Simple_Image)
        self.menuHOLA.addAction(self.actionSet_of_Images)
        self.menuHOLA.addSeparator()
        self.menuHOLA.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionAbout_Interface)
        self.menuHelp.addAction(self.actionAbout_Commands)
        self.menuHelp.addSeparator()
        self.menuSettings.addAction(self.actionChange_settings)
        self.menuBar.addAction(self.menuHOLA.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.LeftMenu.setCurrentIndex(2)
        self.LeftMenu.layout().setSpacing(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_4.setText(_translate("MainWindow", "Extract Background"))
        self.radioButton_3.setText(_translate("MainWindow", "Cromosphere"))
        self.radioButton_2.setText(_translate("MainWindow", "Binary"))
        self.radioButton.setText(_translate("MainWindow", "A ver que meto"))
        self.pushButton_5.setText(_translate("MainWindow", "A"))
        self.pushButton_4.setText(_translate("MainWindow", "B"))
        self.pushButton_7.setText(_translate("MainWindow", "C"))
        self.pushButton_6.setText(_translate("MainWindow", "D"))
        self.pushButton_9.setText(_translate("MainWindow", "E"))
        self.pushButton_8.setText(_translate("MainWindow", "F"))
        self.pushButton_2.setText(_translate("MainWindow", "LOAD"))
        self.pushButton.setText(_translate("MainWindow", "SAVE"))
        self.LeftMenu.setItemText(self.LeftMenu.indexOf(self.P1), _translate("MainWindow", "contrast"))
        self.LeftMenu.setItemText(self.LeftMenu.indexOf(self.P2), _translate("MainWindow", "equalization"))
        self.LeftMenu.setItemText(self.LeftMenu.indexOf(self.P3), _translate("MainWindow", "convolutional filter"))
        self.LeftMenu.setItemText(self.LeftMenu.indexOf(self.P4), _translate("MainWindow", "Softener"))
        self.LeftMenu.setItemText(self.LeftMenu.indexOf(self.P5), _translate("MainWindow", "Contours"))
        self.LeftMenu.setItemText(self.LeftMenu.indexOf(self.P6), _translate("MainWindow", "Página"))
        self.LeftMenu.setItemText(self.LeftMenu.indexOf(self.P7), _translate("MainWindow", "Página"))
        self.menuHOLA.setTitle(_translate("MainWindow", "General Fits"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionLoad_Simple_Image.setText(_translate("MainWindow", "Load a Simple Image"))
        self.actionSet_of_Images.setText(_translate("MainWindow", "Load a Set of Images"))
        self.actionSave.setText(_translate("MainWindow", "Save "))
        self.actionAbout_Interface.setText(_translate("MainWindow", "About Interface"))
        self.actionAbout_Commands.setText(_translate("MainWindow", "About Commands"))
        self.actionChange_settings.setText(_translate("MainWindow", "Change settings"))

